export const TAG_COMMAND_CODE = 'commandCode';
export const TAG_COMMAND_DATA = 'commandData';

// Command codes.
export const COMMAND_MUTE_AUDIO = 97100;
export const COMMAND_UNMUTE_AUDIO = 97101;
export const COMMAND_MUTE_VIDEO = 97102;
export const COMMAND_UNMUTE_VIDEO = 97103;
export const COMMAND_ENTER_TILE_MODE = 97104;
export const COMMAND_EXIT_TILE_MODE = 97105;
export const COMMAND_RAISE_HAND = 97106;
export const COMMAND_SWITCH_CAMERA = 97107;
export const COMMAND_SEND_CHAT_MSG = 97108;
export const COMMAND_GET_CHAT_MESSAGES = 97109;
export const COMMAND_SWITCH_SHARESCREEN = 97110;
export const COMMAND_SET_TILEMODE = 97111;
export const COMMAND_SET_CHATMODE = 97112;

export const COMMAND_USER_JOINED = 97113;
export const COMMAND_USER_LEFT = 97114;
export const COMMAND_REFRESH_PARTICIPANTS = 97115;


